add user update
Sophiscated-Project-Dev/sophis-ecommerce-backend pull request #5
Opened 2022-07-07 14:34 UTC by Olukeye

Implemented a user update method .

2022-07-08 10:44 UTC, ebunedy requested changes
please you can reverse your changes

2022-07-11 15:52 UTC, ebunedy approved these changes

2022-07-11 16:10 UTC, ebunedy approved these changes

2022-07-11 16:22 UTC, Olukeye reviewed
i need this update confirmed.

2022-07-11 16:58 UTC, ebunedy approved these changes

2022-07-12 10:39 UTC, merged